### ISSUE TITLE
Decide on an image registry for SMI assets

### ISSUE THREAD

**Issue by keithmattix** [servicemeshinterface/smi-controller-sdk#19]
At present, SMI adapter images are being stored in an ad-hoc fashion. We need to decide where we should host Docker/OCI images related to the SMI project. We've discussed using the [Github Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/), and it appears that the SMI org already has a presence on [Docker Hub](https://hub.docker.com/u/servicemeshinterface). This issue is for discussion concerning what hosting solution we would like to use.   

(cc @nicholasjackson @phillipgibson)

**Comment by phillipgibson** [comment]
Using GitHub Packages looks to be a viable solution. There are a couple of things we will need to consider. 

1. Depending on the tier of GitHub allows for additional storage and data transfer costs. See [About billing for GitHub Packages](https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages#about-billing-for-github-packages). The project may be at a level to service community downloads, if not we'll have to see about additional solutions.
2. We'll have to determine who has access to publish the packages. This will just be a governance thing we will want to document for the project. It could be a simple as only allowing maintainers etc.

**Comment by nicholasjackson** [comment]
I think the main problem with GitHub packages is that you need a Github Token to pull the packages.

https://github.community/t/download-from-github-package-registry-without-authentication/14407/64

This would mean that folks would need to configure image pull secrets for any of the controller helm charts. I think this would probably be a major blocker for many who just want to try a controller. Maybe we just need to setup an SMI account on DockerHub and push to their public registry?

**Comment by keithmattix** [comment]
According to [GitHub docs](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-visibility-of-container-images-for-an-organization), that limitation appears to have been removed from container images. Furthermore, it looks like there's already a [DockerHub](https://hub.docker.com/u/servicemeshinterface) account for SMI. @bridgetkromhout do you happen to know who has access to that account?

**Comment by bridgetkromhout** [comment]
Looks like I have access to that DockerHub account (which isn't paid afaict). The GitHub org is at a Free level and owned by CNCF.

**Comment by bridgetkromhout** [comment]
Closing due to project archival: https://www.cncf.io/blog/2023/10/03/cncf-archives-the-service-mesh-interface-smi-project/
