### ISSUE TITLE
create dockerhub repo for smi-controller-example

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-controller-sdk#5]
https://github.com/servicemeshinterface/smi-controller-sdk/blob/main/Makefile#L1

**Comment by nicholasjackson** [comment]
@michelleN I don't have access to the SMI docker org, would you be able to create a repo and add a secret for the user and pass to this repo, please?

I can setup the CI to auto push to Docker Hub in the morning.

**Comment by bridgetkromhout** [comment]
Closing due to project archival: https://www.cncf.io/blog/2023/10/03/cncf-archives-the-service-mesh-interface-smi-project/
